server:
  port: 3001
  servlet:
    context-path: /v1/api
spring:
  application:
    name: todos-service
  datasource:
    url: jdbc:postgresql://localhost:5432/todos-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true